server:
  port: 8080


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/drug_information?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 472468302zpy
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
      check-templates: true
      check-template-location: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spc.model #为包下的所有类起别名
mapper:
  mappers:  com.spc.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

