server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://58.206.125.53:3306/course?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: xjtudlc
#    url: jdbc:mysql://202.117.16.167:3306/course?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&&useSSL=false
#    username: testyu
#    password: testyu123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 400
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    check-templates: true
    check-template-location: true
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

##添加了redis 缓存
#spring:
#  redis:
#    datebase: 0
#    host: localhost
#    password:
#    port: 6379
#    debug: false

mybatis:
  mapper-locations: classpath:mapper/*/*/*.xml
  type-aliases-package: com.spc.model #为包下的所有类起别名
#  configuration: #开启二级缓存
#    cache-enabled: true


mapper:
  mappers:  com.spc.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  config: classpath:logging-config.xml
  # 打印sql
  level:
    com:
      spc:
        dao: debug

cas:
  server:
    host:
      url: https://cas.xjtu.edu.cn/
      login_url: https://cas.xjtu.edu.cn/login
#      logout_url: https://cas.xjtu.edu.cn/logout?service=http://58.206.125.53:8080/psc
#      logout_url: https://cas.xjtu.edu.cn/logout?service=http://192.168.16.2:30004/psc
      logout_url: https://cas.xjtu.edu.cn/logout?service=http://localhost:8080/psc
#      logout_url: https://cas.xjtu.edu.cn/logout?service=http://202.117.16.167:8080/psc
app:
  server:
    host:
#      url: http://58.206.125.53:8080/psc
#      url: http://192.168.16.2:30004/psc
      url: http://localhost:8080/psc
#      url: http://202.117.16.167:8080/psc

  login:
    url: /login/cas
  logout:
    url: /logout